services:
  frontend:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    ports:
      - 4200:4200
    networks:
      - bugtracker_net
  backend:
    build:
      context: "../bugtracker2-api/"
      dockerfile: "./Dockerfile"
    ports:
      - 3001:3001
    networks:
      - bugtracker_net
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - bugtracker_net 
networks:
  bugtracker_net:
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt